mergeable:
  pull_requests:
    label:
      or:
        - and:
          - must_include:
              regex: 'release notes: yes'
              message: 'Please add the label "release notes: yes"'
          - must_include:
              regex: '^lang\/'
              message: 'Please add a language ("lang/*") label'
        - must_include:
            regex: 'release notes: no'
            message: 'Please add the label "release notes: no"'
