language: cpp
before_install:
  - sudo add-apt-repository ppa:yjwong/gflags -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtest-dev libgflags-dev python-virtualenv
script:
  - make CONFIG=dbg buildtests_cxx Q=
  - ./tools/run_tests/run_tests.py -l c -t -j 16 -c dbg -s 2.0
  - ./tools/run_tests/run_tests.py -l c++ -t -j 16 -c dbg -s 2.0
  - make clean
  - ./tools/run_tests/run_tests.py -l c -t -j 16 -c opt -s 2.0
  - ./tools/run_tests/run_tests.py -l c++ -t -j 16 -c opt -s 2.0
  - ./tools/run_tests/run_tests.py -l node -t -j 16 -c opt
notifications:
  email: false
